import Container from '../fragments/container.js';
import Card from '../components/card.js';

function IndexScreen() {
	return(
		<Container>
			<Card body="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed arcu non odio euismod lacinia at quis risus. Cras semper auctor neque vitae tempus. Augue eget arcu dictum varius duis at. Morbi tempus iaculis urna id volutpat lacus laoreet non. Semper eget duis at tellus at urna condimentum. Aliquet nec ullamcorper sit amet risus nullam eget felis. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Faucibus turpis in eu mi. Faucibus vitae aliquet nec ullamcorper. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Amet porttitor eget dolor morbi. Id volutpat lacus laoreet non curabitur gravida arcu ac. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Ut lectus arcu bibendum at varius. Ullamcorper a lacus vestibulum sed arcu non odio euismod." title="Test title"/>
			<Card body="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed arcu non odio euismod lacinia at quis risus. Cras semper auctor neque vitae tempus. Augue eget arcu dictum varius duis at. Morbi tempus iaculis urna id volutpat lacus laoreet non. Semper eget duis at tellus at urna condimentum. Aliquet nec ullamcorper sit amet risus nullam eget felis. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Faucibus turpis in eu mi. Faucibus vitae aliquet nec ullamcorper. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Amet porttitor eget dolor morbi. Id volutpat lacus laoreet non curabitur gravida arcu ac. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Ut lectus arcu bibendum at varius. Ullamcorper a lacus vestibulum sed arcu non odio euismod." title="Test title"/>
			<Card body="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed arcu non odio euismod lacinia at quis risus. Cras semper auctor neque vitae tempus. Augue eget arcu dictum varius duis at. Morbi tempus iaculis urna id volutpat lacus laoreet non. Semper eget duis at tellus at urna condimentum. Aliquet nec ullamcorper sit amet risus nullam eget felis. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Faucibus turpis in eu mi. Faucibus vitae aliquet nec ullamcorper. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Amet porttitor eget dolor morbi. Id volutpat lacus laoreet non curabitur gravida arcu ac. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Ut lectus arcu bibendum at varius. Ullamcorper a lacus vestibulum sed arcu non odio euismod." title="Test title"/>
			<Card body="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed arcu non odio euismod lacinia at quis risus. Cras semper auctor neque vitae tempus. Augue eget arcu dictum varius duis at. Morbi tempus iaculis urna id volutpat lacus laoreet non. Semper eget duis at tellus at urna condimentum. Aliquet nec ullamcorper sit amet risus nullam eget felis. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Faucibus turpis in eu mi. Faucibus vitae aliquet nec ullamcorper. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Amet porttitor eget dolor morbi. Id volutpat lacus laoreet non curabitur gravida arcu ac. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Ut lectus arcu bibendum at varius. Ullamcorper a lacus vestibulum sed arcu non odio euismod." title="Test title"/>
			<Card body="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed arcu non odio euismod lacinia at quis risus. Cras semper auctor neque vitae tempus. Augue eget arcu dictum varius duis at. Morbi tempus iaculis urna id volutpat lacus laoreet non. Semper eget duis at tellus at urna condimentum. Aliquet nec ullamcorper sit amet risus nullam eget felis. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Faucibus turpis in eu mi. Faucibus vitae aliquet nec ullamcorper. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Amet porttitor eget dolor morbi. Id volutpat lacus laoreet non curabitur gravida arcu ac. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Ut lectus arcu bibendum at varius. Ullamcorper a lacus vestibulum sed arcu non odio euismod." title="Test title"/>
		</Container>
	);
}

export default IndexScreen;